# Generated by Django 5.2.4 on 2025-09-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="daily_images/"),
                ),
            ],
        ),
    ]
